### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by jgarcy1080**
I have added Menu functionality, a load screen and i have attached sounds to the the main menu buttons. The exit button on the main menu however does nor work

### CODE REVIEW

**Comment by SGTMcClain** [comment]
Wow, you have been busy! I will merge this back into the main build!

**Comment by jgarcy1080** [comment]
Cool beans.
thank you.  The Phantom tile thing is still happening.  It is happening on
the tiles for the red level. ..Level 3

**Comment by SGTMcClain** [comment]
Oh ok, I only fixed them for level one I didn't realize we would have multiple levels

**Comment by jgarcy1080** [comment]
Haha whoops lol

**Comment by jgarcy1080** [comment]
Perhaps we should just show a build with one level?

**Comment by SGTMcClain** [comment]
That's up to you, just let me know and will try to make the changes tonight.  However I don't think I can make any significant changes to what is currently up there until I get back to one of my computers

**Comment by jgarcy1080** [comment]
No worries.  We'll roll on with what we have

**Pull request merged**
